### ISSUE TITLE
No APC40 MkIIx ControlSurface to choose 

### ISSUE THREAD

**Issue by VNVJohny** [xnamahx/APC40_MkIIx#1]
Hello,
i have not the Control Surface APC40 MKIIx from to choose. What make i false?
I have copy the sript in the Midi Remote Script folder, but in Ableton Live 10 can i not it to select!

**Comment by michaelkoder** [comment]
Same for me :(

**Comment by shbadr** [comment]
yeah same here >_<

**Comment by VNVJohny** [comment]
You must copy both Remote Scripts from "xnamahx" Release: APC40MKIIx and _Pushlegacy in the Midi Remote Scripts folder!

**Comment by michaelkoder** [comment]
hello, thanks for your answer, i tryed it and it do not change > i can't see your script in the remote script list in ableton live 10.
I copyed https://github.com/cylab/_PushLegacy to the midi script folder and your's. 
An other advise to make if work please ? :)

**Comment by VNVJohny** [comment]
Please take the Script: "APC40MkIIx", _Pushlegacy" from user: xnamahx

**Comment by michaelkoder** [comment]
i dont see _Pushlegacy on xnamahx, but it's working now, i see your script in my scripts list :). 
Thanks for your time !

**Comment by VNVJohny** [comment]
_Pushlegacy and APCMKIIx under: xnamahx/code/Release/midi remote scripts.zip

**Comment by VNVJohny** [comment]
sorry under:  xnamahx/APC40_MkIIx/code/Release/midi remote scripts.zip

**Comment by xnamahx** [comment]
Glad you make it work @VNVJohny 

Live has little changes over versions that could be breaking compatibility. So it may not work depending on what you are using.

Im waiting till Live 10.1 to support it again.

**Comment by VNVJohny** [comment]
Ok, @xnamahx thanks for your support!

**Comment by michaelkoder** [comment]
Ok ok so I have some questions after some hours with your famous script if you can give us some more informations :) 
> for which version of Ableton live have you done this script please ? Me I am on the 10.0.6
> I ask the fist question because I see some strange things 
	> to remove a clip its not > metronome button + clip / its > "Nudge -" button + clip and "nudge +" button + clip to copy past ( its really cool that you find the way to do this its just not the same controller with you script thanks a loooooooot ! ) :)
	> when I click on metronome button all the clips are yellow and the dont do nothing when I click on them 
	> when I click on user mode I have a sequencer system but you dont give us informations about this new part of the controller > if you can its cool :)
	> the shift button + numbers buttons to quantize do not work any more 
	> the metronome button do not work to activate/desactivate the metronome 
	> I often see a kind of volume system on the "stop all clips" buttons on the right side too but I dont see effects 

> I dont know if I made a good installation or If I have Ableton live version problem ...? 
> I took the _Pushlegacy here > https://github.com/cylab/_PushLegacy ( I did not finded your's on your repo.. there is no code directory on your script code ... ) 		

Thanks again for your time ! You rock !

**Comment by VNVJohny** [comment]
Please read xnamahx comment!

**Comment by michaelkoder** [comment]
cue level do not work and A/B fader lignt assigniation not working too ... :( :( it's realy problematic ... 
A way to just add the shorcuts to remove clips and copy past to the original apc40 mk2 midi script ? 
I am web developer i can code even if i dont realy know python.

**Comment by xnamahx** [comment]
@mistermika Sorry about the long hours with this script. This [commit ](https://github.com/xnamahx/APC40_MkIIx/commit/b284ea5ccd1243aa8f5b5e4528fbdce94dc730c5) may contain the changes you want.

 Ableton's MIDI Scripts are a nice excuse to learn Python.

**Comment by michaelGreenDev** [comment]
@xnamahx  ho thank you so much ! :) i try this evening. 
Dont be sorry its realy cool to be able to delete and copy past clips thanks to your script ! It was realy missing before now its realy more usefull ! 
Have a good day !

**Comment by VNVJohny** [comment]
@xnamahx Sorry, I do not know what to do, do I have to replace the modified Python files with the existing ones? Or is this an independent new script?

**Comment by michaelkoder** [comment]
@VNVJohny It’s a new script that you have to copy on the midi script folder of ableton + this one > https://github.com/cylab/_PushLegacy ( 2 folders to add in total )

**Comment by michaelkoder** [comment]
@xnamahx hello, you told tha you made a commit to correct the problems that i told you. I have to take the version of your commit so ? This one ? > https://github.com/xnamahx/APC40_MkIIx/tree/b284ea5ccd1243aa8f5b5e4528fbdce94dc730c5 
It'a version with only copy/past/remove clip shorcuts added to the original APC40 midi script ? 
Thanks :)

**Comment by xnamahx** [comment]
@mistermika Yes, that's an old commit on the beginning of this script where I copy the original that comes with ableton and just added the copy and delete shortcuts. Then I tried to merge the APCSequencer and other stuff.

It will not work because I leave "pydevd" imports for debug reasons and that will break dependency for you. Just delete those lines.

**Comment by xnamahx** [comment]
added a version with only copy/paste and delete here https://github.com/xnamahx/APC40_MkIIx/releases/download/01a/APC40_MkIIx.zip
